"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IRandomizer__factory = exports.DareDropContract__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var DareDropContract__factory_1 = require("./DareDropContract__factory");
Object.defineProperty(exports, "DareDropContract__factory", { enumerable: true, get: function () { return DareDropContract__factory_1.DareDropContract__factory; } });
var IRandomizer__factory_1 = require("./IRandomizer__factory");
Object.defineProperty(exports, "IRandomizer__factory", { enumerable: true, get: function () { return IRandomizer__factory_1.IRandomizer__factory; } });
