/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DareDropContract } from "./DareDropContract";
export type { IRandomizer } from "./IRandomizer";
